### ISSUE TITLE
Changes for Charlie:

### ISSUE THREAD

**Issue by Michallo538** [jsomaiya9/2122-Advanced-Programming-Group-A#1]
### User 
 - Remove search from the tables, there are only 3 courses so its not needed.
 
### Staff 
-Add/Edit/Delete for courses and modules, Assignment doesn't show requirements for those.

### Page Designs
- The Top and bottom of the pages should stay the same through all pages, for example the links 'About Us -Courses - Contact Information' should stay the same without adding register to  it as you did in one of the pages.

**Comment by charlieroper17** [comment]
Updates made: 

User - Descriptions and case edited 
Staff - Changes made 
Pages designs have also been edited  Please see below for documents they will also be uploaded to the repository.

[USE Case Descriptions .docx](https://github.com/jsomaiya9/2122-Advanced-Programming-Group-A/files/8492173/USE.Case.Descriptions.docx)
 
![USE Case Edited](https://user-images.githubusercontent.com/98821371/163474829-a69a8453-3071-46f5-b8ca-b83962100c4c.PNG)

[Prototype Design Pages.docx](https://github.com/jsomaiya9/2122-Advanced-Programming-Group-A/files/8492215/Prototype.Design.Pages.docx)

**Comment by charlieroper17** [comment]
Event Tables also updated to reflect changes 

[Event Tables.docx](https://github.com/jsomaiya9/2122-Advanced-Programming-Group-A/files/8492224/Event.Tables.docx)
